### ISSUE TITLE
question about learning rate

### ISSUE THREAD

**Issue by Wangweiyao** [NVlabs/RVT#17]
hi, just a quick question regarding learning rate. in your paper it says "an initial learning rate of 2.4 × 10−4" but in code it shows 1 x 10-4 , if we multiply by 3*8, it would be 2.4 × 10−3, would that be right?

**Comment by imankgoyal** [comment]
@Wangweiyao  Good catch! It seems like there is a typo in the paper. We will verify and update it in the paper.

**Comment by Wangweiyao** [comment]
got it, thx!
