### ISSUE TITLE
What is low_dim_state.

### ISSUE THREAD

**Issue by obiza-theaiinstitute** [NVlabs/RVT#19]
What do the 4 dimensions in `obs["low_dim_state"]` correspond to? I think the last one is the gripper open/closed bit?

Thanks!

**Comment by imankgoyal** [comment]
Hi @obiza-theaiinstitute,

They are same as [PerAct](https://github.com/peract/peract/blob/b73cf504567122f81912964943a16cd83920e4d9/agents/peract_bc/perceiver_lang_io.py#L143). Apart form gripper open and time, there is seperate value for each of the gripper fingers. That might be potentially unncessary (I am not sure), but it here I have kept it consistent as PerAct.

**Comment by obiza-theaiinstitute** [comment]
I see, thanks Ankit!
