### ISSUE TITLE
proprioception dimension

### ISSUE THREAD

**Issue by Harimus** [NVlabs/RVT#20]
Hi first of all thank you for the amazing work of RVT.

I have a question. I'm trying to reproduce some of the results on the real-robot setting with a Franka robot, and I'm trying to understand the proprioception data. According to the MTV config the `proprioception_dim` is 4.  What does those 4dim represent? If it's the joint position I assume it should bigger, and if it was cartesian position of the end-effector I assume it is either 3 or 6 (or 7 if quaternion).

Thank you in advance

**Comment by imankgoyal** [comment]
Hi @Harimus,

I think #19 should address your question. Let me know if any questions still remain.

Best,
Ankit

**Comment by Harimus** [comment]
ah wow I missed that one somehow, thank you!
