### ISSUE TITLE
About models training

### ISSUE THREAD

**Issue by TeleeMa** [NVlabs/RVT#26]
Thank you for your great work!

When I trained the model from scratch, I encountered that the training stucks like this:
<img width="1680" alt="Screenshot 2023-10-09 at 12 20 04 PM" src="https://github.com/NVlabs/RVT/assets/33897627/c14d1f18-4fc5-44c3-b994-03f8ff2f84d4">.

The GPU utilization is MAX, but the GPU memory is very low. 
<img width="1667" alt="Screenshot 2023-10-09 at 12 19 50 PM" src="https://github.com/NVlabs/RVT/assets/33897627/dac90d61-1e25-49e0-9bda-a0c519295303">

So is it normal, or have you encountered the same situation?

Thanks.

**Comment by imankgoyal** [comment]
Hi,

Thanks for your interest in our work. I haven't seen this issue at my end so not sure what is going on. I would suggest putting some print statements at various locations in the `train.py` script to debug the issue.

Best,
Ankit

**Comment by TeleeMa** [comment]
Hi,

Thank you for your reply. I have solved the problem after changing the docker environment. I will close the issue.

Best,
Teli
