### ISSUE TITLE
Code for evaluating on real Franka Panda

### ISSUE THREAD

**Issue by lyshuga** [NVlabs/RVT#3]
Hi,

Thank you for such a great paper. In your demonstrations I have noted that you evaluated your network on real Franka Panda as well, and I was wondering if you could publish the code for evaluation on real robot as well.

Thank you in advance.

**Comment by imankgoyal** [comment]
Hi,

Thank you so much for you interest in our work.

Unfortunately, we do not plan to release the code for real robot evaluation at the moment as it is not clean enough and very specific to our robot setup. However, the network and the training is setup in the real world is very similar to what we have released. We will be happy to assist with any issues or more details that you might need for the real robot evaluation.
