### ISSUE TITLE
Questions about the loss

### ISSUE THREAD

**Issue by SatireY** [NVlabs/RVT#41]
I noticed that the predicted 3D position Action was not output during the training process, so why not directly use the Action of the expert trajectory and the Action of the strategy output as the loss function? Is it derivable to further calculate the operation of the 3D loc when the MVT model outputs the heat map? Looking forward to your reply, thank you.

**Comment by imankgoyal** [comment]
Hi @SatireY, 

I'm sorry for not getting back to you sooner. We do not directly use the 3D position but rather the heatmaps for loss. Deriving a differentiable function from the heatmap to the 3D position is non-trivial. There might be some tricks to do so, like taking a weighted average, etc., but we do not investigate them. 

That being said, I would be very interested in what results you get with them. Please keep us posted if you find anything.

Best,
Ankit
