### ISSUE TITLE
what is the minimum GPU mem required for training the RVT-2 model

### ISSUE THREAD

**Issue by ruili3** [NVlabs/RVT#47]
Hello,

Thanks for the nice work! I noticed that you use 8 V100 GPUs for model training. What are the minimum GPU resources to train the model based on the default setting (e.g., batch size)? I may not have as many as up to 8 V100, so I'd be grateful for your feedback on the computation cost. Thanks.

**Comment by imankgoyal** [comment]
Hello, 

Sorry for the late reply. We used 16GB memory for each V100 (128GB in total). In general, RVT-2 should be the cheapest model to train for any computational resource. I would be very interested in what speed you observe on other GPU setups. Please make sure to scale the batch size given your GPU.

Best,
Ankit
