### ISSUE TITLE
Model traind form scratch  can't work well on place_cups and stack_blocks

### ISSUE THREAD

**Issue by Daisling** [NVlabs/RVT#59]
Thanks for your great work! can you tell me some method to reach the avarage rate in paper?
I use 4 a100 GPUs to train RVT2 from scratch, and the batchsize is 48 for each GPU.
I use the 99th model to evaluate and the result is :
![image](https://github.com/user-attachments/assets/d9d9f6d5-48bd-4358-aad0-bc87ad476247)

the success rate dosen't look nice in  place_cups and stack_blocks , and the avarage rate is 77.11.

**Comment by bitw1z** [comment]
Hello, how many epochs did you use for the training? How did you resolve the issues in place cups and stack_blocks?
