### ISSUE TITLE
How to get true colors in the inference image ?

### ISSUE THREAD

**Issue by rebecajohn** [NVlabs/RVT#62]
![Screenshot from 2024-10-09 02-15-10](https://github.com/user-attachments/assets/2b0658bf-d847-4d27-b2c7-bfade7dfd977)

**Comment by imankgoyal** [comment]
Try this: https://github.com/NVlabs/RVT/issues/5

**Comment by rebecajohn** [comment]
@imankgoyal  Thank you :)
