### ISSUE TITLE
num.of demonstrations used during training ?

### ISSUE THREAD

**Issue by rebecajohn** [NVlabs/RVT#65]
Hi @imankgoyal , The model was trained using how many demonstrations for each task in RVT and RVT2?

**Comment by rebecajohn** [comment]
I am curious to know why the performance in some tasks that was trained  on 10 demonstrations exceed than that of 100 demonstrations ?

**Comment by imankgoyal** [comment]
Hi @rebecajohn, 

We use 100 demonstrations for each task in RLBench and 10 for each task in real. 100 was used in RLBench to keep the benchmark consistent with prior works. We haven't tested with 10 demonstrations in RLBench. Do you mean on some tasks, you get better results with 10 demonstrations in RLBench?

**Comment by rebecajohn** [comment]
Hello @imankgoyal ,Yes. for example in RLBench , for RVT ,in Turn Tap task gives Avg success  for 10 demonstrations as 96 , but when the demonstrations are increased to 100 , Avg. success  decreases to 76 , even for some other tasks in those 18 tasks , we get small decrease in Avg. success.
