### ISSUE TITLE
 experiments with Different Resolution of images ?  

### ISSUE THREAD

**Issue by rebecajohn** [NVlabs/RVT#70]
Any ablation study on increase in resolution vs success rate ?

**Comment by VamsiYK** [comment]
I found it in 6.3 Ablations, its 220 and 100 . So my question is where is 128 , since the data is same as from the peract.

**Comment by rebecajohn** [comment]
220 and 100 are the resolutions of the rendered images.

**Comment by VamsiYK** [comment]
How many virtual images were taken for mvt ?
