### ISSUE TITLE
About eval error：“RuntimeError: Handle Panda does not exist”

### ISSUE THREAD

**Issue by LogSSim** [NVlabs/RVT#73]
Why does this error occur?
"
RuntimeError: Handle Panda does not exist.
QMutex: destroying locked mutex
xvfb-run: error: problem while cleaning up temporary directory
"

**Comment by LogSSim** [comment]
> Why does this error occur? " RuntimeError: Handle Panda does not exist. QMutex: destroying locked mutex xvfb-run: error: problem while cleaning up temporary directory "

Oh, I fix it

**Comment by IrvingF7** [comment]
> > Why does this error occur? " RuntimeError: Handle Panda does not exist. QMutex: destroying locked mutex xvfb-run: error: problem while cleaning up temporary directory "
> 
> Oh, I fix it

Hi! Do you mind explaining how you fixed it? Thank you in advance
